### ISSUE TITLE
模型LOADING代码已经修复好了，大家可以继续在线上生成

### ISSUE THREAD

**Issue by Y1ran** [EssayKillerBrain/WriteGPT#7]
BUG找了很久，蛋疼

**Comment by lvxiayu** [comment]
你说巧不巧还是有出错
/home Cloning into 'EssayKiller_V2'... remote: Enumerating objects: 13, done. remote: Counting objects: 100% (13/13), done. remote: Compressing objects: 100% (10/10), done. remote: Total 493 (delta 1), reused 4 (delta 0), pack-reused 480 Receiving objects: 100% (493/493), 206.32 MiB | 33.05 MiB/s, done. Resolving deltas: 100% (138/138), done. Checking out files: 100% (274/274), done. /home/EssayKiller_V2/LanguageNetwork/GPT2/finetune --2020-11-11 04:22:57--  https://docs.google.com/uc?id=1ajR-yVWmZC_z7HgNjz4tivNz-vUCgKBC&amp;export=download Resolving docs.google.com (docs.google.com)... 172.217.5.238, 2607:f8b0:4004:806::200e Connecting to docs.google.com (docs.google.com)|172.217.5.238|:443... connected. HTTP request sent, awaiting response... 200 OK Length: unspecified [text/html] Saving to: ‘trained_models/model.ckpt-280000.data-00000-of-00001’      0K                                     44.2M=0s 2020-11-11 04:22:57 (44.2 MB/s) - ‘trained_models/model.ckpt-280000.data-00000-of-00001’ saved [3085] Couldn't download the file :-( model.ckpt-280000.i 100%[===================&gt;]  70.68K  --.-KB/s    in 0.003s   model.ckpt-280000.m 100%[===================&gt;]  12.49M  --.-KB/s    in 0.1s     模型下载完成，Git项目已构建，请继续点击下方的▶️




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EssayKillerBrain/EssayKiller_V2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月10日(星期二) 晚上11:23
收件人:&nbsp;"EssayKillerBrain/EssayKiller_V2"<EssayKiller_V2@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[EssayKillerBrain/EssayKiller_V2] 模型LOADING代码已经修复好了，大家可以继续在线上生成 (#7)





 
BUG找了很久，蛋疼
